### PR TITLE
Joshua Hill - Autonomy Bootcamp PR

### PR DESCRIPTION
**Pull request by joshua-hill**

### CODE REVIEW

**Review by mgupta27 — CHANGES_REQUESTED** [review]
For some reason the `.ipynb` file does not show up correctly. Can you fix this and re-request for a review?

**Comment by Trotyl15** [comment]
Can you add a logging screenshot or a graph showing the accuracy vs epoches?

**Comment by joshua-hill** [comment]
Okay, I added the image of the accuracy vs epoch plot

**Review by Trotyl15 — APPROVED** [review]
Overall looks good:), in the future, please organize your codes in to functions to improve readability. Welcome onboard! Check out this document for onboarding instructions: https://uwarg-docs.atlassian.net/wiki/spaces/CV/pages/2060353537/Autonomy+Onboarding

**Pull request closed without merging**
