### PR TITLE
cv bootcamp PR

### PR DESCRIPTION
**Pull request by HarryFung22**

### CODE REVIEW

**Comment by rayjinghaolei** [comment]
Any particular reason that the val_loader has twice the batch size? 
image

**Comment by rayjinghaolei** [comment]
It would be a good idea to organize your code a bit, It is good that you do have functions and classes, you just need to also group the rest of the commands/scripts together into chunk/functions that makes, sense, for example, data_preprocessing, setup_train_configs and etc.

**Comment by HarryFung22** [comment]
@rayjinghaolei i have implemented functions and organized the code

**Comment by rayjinghaolei** [comment]
Looks great now, Welcome to the CV team. https://uwarg-docs.atlassian.net/l/cp/BBG8vtUA here is the onboarding documentation

**Pull request closed without merging**
