### PR TITLE
Computer Vision Bootcamp

### PR DESCRIPTION
**Pull request by prerak77**

### CODE REVIEW

**Comment by Trotyl15** [comment]
Hey Prerak, can you include the accuracy in your terminal output or in a graph?

**Comment by prerak77** [comment]
I have added Accuracy of the model to the terminal output and upload an image of the new output as well.

**Comment by Trotyl15** [comment]
Can you increase the accuracy to 70%? Your loss graph looks a bit overfitting, try adjusting the step size, adding data augmentation, or different optimizers.

**Comment by prerak77** [comment]
I have increased the Accuracy of the model to 72% by using a different optimizer and adding some data augmentation

**Comment by Trotyl15** [comment]
Looks good now! Please check this out for onboarding instructions. https://uwarg-docs.atlassian.net/wiki/spaces/CV/pages/2060353537/CV+Onboarding Welcome to the team!

**Pull request closed without merging**
