### PR TITLE
CV_Bootcamp_Take_2

### PR DESCRIPTION
**Pull request by Neel49**

### CODE REVIEW

**Comment by Trotyl15** [comment]
Hey Neel, can you break your code into functional blocks? That would make it more organized

**Comment by Neel49** [comment]
Sorry for the late reply, midterm week. But could you elaborate what you mean by "functional blocks"?

The imports, importing the data set, data preprocessing, model layout, model training, and viewing model accuracy are all currently separate code blocks.

**Comment by Trotyl15** [comment]
python functions like the one you made for scale_images. We just want to make sure people can be uses to our style guide and apply it in our future projects :D

**Comment by Neel49** [comment]
Umm, sorry, but I'm still a little confused; I followed the snake case rule for naming the scale_images function, but if you are referring to the fact the function declaration and use as a parameter in the training_set.map() function are in the same code block; that's the only way I could get it to work. I genuinely don't know why but if I didn't have that code block set up the way I did, I would get errors when I went to train. I kind of solved that issue through trial and error.

**Comment by Trotyl15** [comment]
oh ic. That's alright, just remember to put codes in functions in future projects and that will be fine.

**Review by Trotyl15 — APPROVED** [review]

**Comment by Trotyl15** [comment]
Sorry, I forgot to mention that please check this out https://uwarg-docs.atlassian.net/wiki/spaces/CV/pages/2060353537/CV+Onboarding for our onboarding instructions. Welcome to the team!

**Pull request closed without merging**
