### PR TITLE
added red thresholding

### PR DESCRIPTION
**Pull request by zarinaaa**
Function thresholds red regions of an image.

### CODE REVIEW

**Comment by CoatedMoose** [comment]
There are a few files here that shouldn't be version controlled. I forget the complete list of files cmake generates and which are created, but I know that `CMakeCache.txt`, `Makefile`, and the generated binary `redthreshold`  shouldn't be version controlled. I am not sure about this, but I think the entire contents of `CMakeFiles` directory shouldn't be either. You can/should add them to the gitignore so they don't show up in source control erroneously.

**Comment by sergei1152** [comment]
@zarinaaa If you're wondering how to do what Andrew just said, you need to use a `.gitignore` file. If you click on the files changed tab above ^^ to view what you changed you'll notice ~4000 lines of new code, most of which is generated and makes figuring out what you did alot harder. Since this isn't the computer vision repo and we're not merging it in its not a problem, but something you should keep in mind for the future :+1:

**Comment by sergei1152** [comment]
Also it may not be applicable to your changes but you may want to split up the work you do into multiple commits. Doing this keeps the commits small and easier to track. Again, something you may want to keep in mind in the future.

**Comment by benjaminwinger** [comment]
@zarinaaa regarding ignoring generated files, if you create a directory called build and run cmake and make inside there then the generated files will both be ignored (since the build directory is already in the gitignore) and then you also won't have build files alongside your source files.

**Comment by zarinaaa** [comment]
Thank you for the feedback!! I noticed that most of those files were generated, but I honestly wasn't sure what I should put in a .gitignore file as this was my first time using Cmake. Oops! I'll keep it in mind for next time :)

**Comment by uwuarg** [comment]
Can one of the admins verify this patch?

**Comment by chrishajduk84** [comment]
Not sure who this is. But please you your personal account and not the wargdogs account. Also, this pull request is stale, improperly coded and will be closed.

**Comment by benjaminwinger** [comment]
It's Jenkins as usual. I was setting up pull request building for the bootcamp. Do you want me to create a separate account just for jenkins? (considering real people occasionally use the wargdogs account)

**Comment by uwuarg** [comment]
No... Its okay. I didn't know Jenkins asks about the status of patches.

**Comment by chrishajduk84** [comment]
Oh the irony.... I meant to post with this account.

**Comment by CoatedMoose** [comment]
Classic Chris.

**Comment by zarinaaa** [comment]
omg.... thanks for this throwback to my first (and worst 😜 ) ever PR lol

**Comment by chrishajduk84** [comment]
lol

**Pull request closed without merging**
